  AWSTemplateFormatVersion: '2010-09-09'
  Parameters:
    # Parametros para la instancia ec2  
    InstanceType:
      Description: EC2 instance type
      Type: String
      Default: t2.small
      AllowedValues:
        - t1.micro
        - t2.nano
        - t2.micro
        - t2.small
        - m1.small
      ConstraintDescription: Use a valid EC2 instance type.
    KeyPairName:
      Description: EC2 KeyPair to enable SSH access to the instances.
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: Use the name of an existing EC2 KeyPair
    # Parametros para redes
  Resources:
    # Creacion de una instancia EC2
    MyInstance:
      Type: "AWS::EC2::Instance"
      Properties:
  #      IamInstanceProfile: String
        AvailabilityZone: us-east-1a
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        ImageId: "ami-042e8287309f5df03"
        SecurityGroups:
          - !ImportValue SecurityGroupSSH
        UserData:
          Fn::Base64:  |
              #!/bin/bash
              sudo apt update -y
              sudo apt install apache2 php php-mysql -y
              sudo cd /var/www/html
              sudo rm -rf index.html
              sudo wget https://wordpress.org/latest.tar.gz &&  wget https://s3.amazonaws.com/bucketforwordpresslab-donotdelete/htaccess.txt
              sudo tar -xvzf latest.tar.gz
              sudo cp -r htaccess.txt /var/www/html/.htaccess
              sudo cp -r wordpress/* /var/www/html/
              sudo rm -rf wordpress
              sudo rm -rf latest.tar.gz
              sudo chmod -R 755 wp-content
              sudo rm -f /var/www/html/index.html
              sudo chown www-data:www-data -R /var/www/html

              