AWSTemplateFormatVersion: '2010-09-09'
Parameters:  
  VPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id
  SubnetIDs:
    Description: Subnet IDs that is a List of Subnet Id
    Type: "List<AWS::EC2::Subnet::Id>"
Resources:
# Creacion de un security group
  MySecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access in port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      VpcId: !Ref VPC
Outputs:
  StackSSHSecurityGroup:
    Description: Security Group SSH output
    Value:
      'Fn::GetAtt':
        - StackSSHSecurityGroup
        - GroupId
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-SecurityGroupID'